compile:
	g++ server.cpp -o server -std=c++11 -lpthread
	g++ client.cpp -o client

server:
	g++ server.cpp -o server -std=c++11 -lpthread

client:
	g++ client.cpp -o client

gentransc:
	g++ gen_transactions_file.cpp -o gentransc -std=c++11 

clean:
	rm server client gentransc